# <center> INTRODUCTION À PYTHON POUR L'ÉCONOMIE EMPIRIQUE</center>
## <center> COURS 2: </center>
## <center> LECTURE ET ANALYSE DE BASIQUE DE DONNÉES </center>
#### <center>Michal Urdanivia (UGA)</center>
#### <center> michal.wong-urdanivia@univ-grenoble-alpes.fr </center>

### <center>1. PRÉSENTATION </center>

Nous allons dans ce notebook nous servir de données de AirBnb pour la ville de Oslo, lesquelles sont disponibles à **Inside AirBnb**: 

http://insideairbnb.com/get-the-data.html

Un dictionnaire des variables disponibles est à consulter [ici](https://docs.google.com/spreadsheets/d/1iWCNJcSutYqpULSQHlNyGInUvHg2BoUGoNRIGa6Szc4/edit#gid=982310896).

Les données que nous employons concernent:

- les listings,
- les prix.

In [15]:
# Importation de bibliothèques utilisées

import numpy as np
import pandas as pd

### <center>2. LECTURE DES DONNÉES </center>

La bibliothèque Pandas contient plusieurs fonction pour lire des données qui se distinguent par le format dans lequel les données se présentent. Par exemple, notons les fonction suivantes,

- `pd.read_csv()`
- `pd.read_html()`
- `pd.read_parquet()`

Pour ce qui va suivre, on peut noter `pd.read_csv()` peut importer des données depuis le web.

La première base de données que nous importons contient les listings de AirBnb pour la ville de Oslo.

In [16]:
url_listings = "https://data.insideairbnb.com/norway/oslo/oslo/2025-09-29/visualisations/listings.csv"
df_listings = pd.read_csv(url_listings)

La deuxième base de données contient des informations sur les montants(prix) des transactions et le calendrier correspondant. Ces données se présentent en format compressé. Pour les importer directement on utilise ici l'option  `compression`.

In [17]:
url_prices = "https://data.insideairbnb.com/norway/oslo/oslo/2025-09-29/data/calendar.csv.gz"
df_prices = pd.read_csv(url_prices, compression="gzip")

### <center>3. EXPLORATION BASIQUE DES DONNÉES </center>

> Méthodes
>
>- `info()`
>- `head()`
>- `describe()`

L'appel de' `info()` data frame pandas donne des informations sur les données dans leur ensemble et les variables présentes.

In [18]:
df_listings.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12160 entries, 0 to 12159
Data columns (total 18 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   id                              12160 non-null  int64
 1   name                            12160 non-null  object
 2   host_id                         12160 non-null  int64
 3   host_name                       12156 non-null  object
 4   neighbourhood_group             0 non-null      float64
 5   neighbourhood                   12160 non-null  object
 6   latitude                        12160 non-null  float64
 7   longitude                       12160 non-null  float64
 8   room_type                       12160 non-null  object
 9   price                           8703 non-null   float64
 10  minimum_nights                  12160 non-null  int64
 11  number_of_reviews               12160 non-null  int64
 12  last_review                     10109 non-null  object
 13  reviews_per_month               10109 non-null  float64
 14  calculated_host_listings_count  12160 non-null  int64
 15  availability_365                12160 non-null  int64
 16  number_of_reviews_ltm           12160 non-null  int64
 17  license                         0 non-null      float64
dtypes: float64(6), int64(7), object(5)
memory usage: 1.7+ MB

Avec l'option `verbose=False` on peut se contenter d'informations sur la dimension des données.

In [19]:
df_listings.info(verbose=False)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12160 entries, 0 to 12159
Columns: 18 entries, id to license
dtypes: float64(6), int64(7), object(5)
memory usage: 1.7+ MB

On peut aussi afficher des lignes de la base afin de voir à quoi cela ressemble. Pour cela on peut utiliser la méthode `head()`  qui par défaut affiche les 5 premières lignes. Avec `head(nbr)` ou `head(n = nbr)`où `nbr` est un entier positif on affiche les `nbr` premières lignes.

In [20]:
df_listings.head()

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365,number_of_reviews_ltm,license
0,42932,"Charming apartment, Oslo Center, Ro",187463,Cecilie,NaN,Frogner,59.91201,10.72455,Entire home/apt,2166.0,4,55,2025-08-12,0.37,2,2,1,NaN
1,71725,Central big room - ap with balcony,368229,Reidun,NaN,Gamle Oslo,59.90795,10.77987,Private room,467.0,14,59,2025-09-01,0.33,1,257,3,NaN
2,85902,"Eclectic design home, super central",250159,Melissa,NaN,Gamle Oslo,59.91074,10.77232,Entire home/apt,1800.0,2,82,2025-05-21,0.47,1,28,1,NaN
3,149776,Bird's nest in the heart of Oslo,714768,Henrik,NaN,St. Hanshaugen,59.92398,10.74787,Private room,946.0,4,46,2025-08-29,0.27,2,365,2,NaN
4,165218,"Bedroom, nice riverview, in Oslo",787976,Jon,NaN,Sagene,59.93750,10.76554,Private room,NaN,2,32,2025-09-14,0.19,1,0,8,NaN

La méthode `describe()` permet d'afficher une description des données. Si plusieurs variables sont présentes il est préférable d'afficher une transposée du tableau de sortie par défaut en utilisant l'attribut `.T`.

In [21]:
df_listings.describe().T[:5]

,count,mean,std,min,25%,50%,75%,max
id,12160.0,9.389567e+17,4.891816e+17,42932.00000,7.256471e+17,1.081037e+18,1.336992e+18,1.519835e+18
host_id,12160.0,1.970386e+08,2.008178e+08,43067.00000,3.740636e+07,1.088633e+08,3.319753e+08,7.208439e+08
neighbourhood_group,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
latitude,12160.0,5.992184e+01,2.041879e-02,59.81290,5.991322e+01,5.992298e+01,5.993185e+01,6.004156e+01
longitude,12160.0,1.076128e+01,4.295326e-02,10.59105,1.073875e+01,1.076316e+01,1.078037e+01,1.094294e+01

On peut choisir les variables à afficher avec l'option `include` avec `include='all'`
pour inclure aussi les variables catégorielles.

In [22]:
df_listings.describe(include='all').T[:5]

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
id,12160.0,NaN,NaN,NaN,938956749541327360.0,489181585691929984.0,42932.0,725647078285722752.0,1081036578575816064.0,1336992415769130240.0,1519835182984056576.0
name,12160,11133,Leilighet i Oslo,29,NaN,NaN,NaN,NaN,NaN,NaN,NaN
host_id,12160.0,NaN,NaN,NaN,197038596.848273,200817846.646969,43067.0,37406361.75,108863268.0,331975321.75,720843915.0
host_name,12156,4203,Urban,88,NaN,NaN,NaN,NaN,NaN,NaN,NaN
neighbourhood_group,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

L'attribut `.columns` donne une liste des colonnes dans la base de données.

In [23]:
df_listings.columns

Index(['id', 'name', 'host_id', 'host_name', 'neighbourhood_group',
       'neighbourhood', 'latitude', 'longitude', 'room_type', 'price',
       'minimum_nights', 'number_of_reviews', 'last_review',
       'reviews_per_month', 'calculated_host_listings_count',
       'availability_365', 'number_of_reviews_ltm', 'license'],
      dtype='object')

Pour obtenir l'indice nous employons l'attribut `.index`,

In [24]:
df_listings.index

RangeIndex(start=0, stop=12160, step=1)

### <center>4. SÉLECTION DE DONNÉES </center>

Pour accéder à une seule colonne du data frame on utilise le nom de cette colonne comme la clé d'un élément dans un objet de type dictionnaire.

In [25]:
df_listings['price']

0        2166.0
1         467.0
2        1800.0
3         946.0
4           NaN
          ...
12155     346.0
12156    1496.0
12157     732.0
12158     435.0
12159    1086.0
Name: price, Length: 12160, dtype: float64

L'attribut `.iloc` permet la sélection de lignes et colonnes à partir de l'indice,

In [26]:
df_listings.iloc[:7, 5:9]

    neighbourhood  latitude  longitude        room_type
0         Frogner  59.91201   10.72455  Entire home/apt
1      Gamle Oslo  59.90795   10.77987     Private room
2      Gamle Oslo  59.91074   10.77232  Entire home/apt
3  St. Hanshaugen  59.92398   10.74787     Private room
4          Sagene  59.93750   10.76554     Private room
5          Sagene  59.93024   10.75964  Entire home/apt
6      Nordstrand  59.84704   10.77780  Entire home/apt

Pour ne sélectionner que des lignes ou colonnes on utilise `:` sur la dimension(lignes ou colonnes) où la sélection ne s'applique pas.

In [27]:
df_listings.iloc[:, 5:9].head()

    neighbourhood  latitude  longitude        room_type
0         Frogner  59.91201   10.72455  Entire home/apt
1      Gamle Oslo  59.90795   10.77987     Private room
2      Gamle Oslo  59.91074   10.77232  Entire home/apt
3  St. Hanshaugen  59.92398   10.74787     Private room
4          Sagene  59.93750   10.76554     Private room

Quant à l'attribut `.loc` il permet d'utiliser les noms des lignes et colonnes.

In [28]:
df_listings.loc[:, ['neighbourhood', 'latitude', 'longitude']].head()

    neighbourhood  latitude  longitude
0         Frogner  59.91201   10.72455
1      Gamle Oslo  59.90795   10.77987
2      Gamle Oslo  59.91074   10.77232
3  St. Hanshaugen  59.92398   10.74787
4          Sagene  59.93750   10.76554

Et on peut aussi sélectionner des rangs.

In [29]:
df_listings.loc[:, 'neighbourhood':'room_type'].head()

    neighbourhood  latitude  longitude        room_type
0         Frogner  59.91201   10.72455  Entire home/apt
1      Gamle Oslo  59.90795   10.77987     Private room
2      Gamle Oslo  59.91074   10.77232  Entire home/apt
3  St. Hanshaugen  59.92398   10.74787     Private room
4          Sagene  59.93750   10.76554     Private room

Une manière rapide de sélectionner des **colonnes numériques** est la fonction
`.select_dtypes()` fonction.

In [30]:
df_listings.select_dtypes(include=['number']).head()

,id,host_id,neighbourhood_group,latitude,longitude,price,minimum_nights,number_of_reviews,reviews_per_month,calculated_host_listings_count,availability_365,number_of_reviews_ltm,license
0,42932,187463,NaN,59.91201,10.72455,2166.0,4,55,0.37,2,2,1,NaN
1,71725,368229,NaN,59.90795,10.77987,467.0,14,59,0.33,1,257,3,NaN
2,85902,250159,NaN,59.91074,10.77232,1800.0,2,82,0.47,1,28,1,NaN
3,149776,714768,NaN,59.92398,10.74787,946.0,4,46,0.27,2,365,2,NaN
4,165218,787976,NaN,59.93750,10.76554,NaN,2,32,0.19,1,0,8,NaN

Les autres types sont:

- `object` pour les chaînes de caractère,
- `bool` pour les booléens,
- `int` pour les entiers,
- `float` pour les floats(par abus nous dirons qu'il s'agit des nombres réels)

On peut aussi sélectionner des lignes à partir d'un opérateur logique,

In [31]:
df_listings.loc[df_listings['number_of_reviews']>500, :].head()

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365,number_of_reviews_ltm,license
18,760266,In the heart of the city,3996622,Per Martin,NaN,Gamle Oslo,59.912159,10.760248,Private room,1172.0,1,1045,2025-09-15,6.71,1,356,101,NaN
19,761018,Lovely bedroom in beautiful area.,4011871,Mona Johanne,NaN,Frogner,59.917550,10.714280,Private room,443.0,1,1271,2025-09-24,8.16,1,0,86,NaN
33,1250723,"Down town, by the central station",1616331,Anita,NaN,Grünerløkka,59.917530,10.754800,Private room,706.0,1,686,2025-09-21,4.59,1,355,23,NaN
37,1310319,Elegant room with privat bathroom - Oslo,7121844,Line-Kirsti,NaN,Frogner,59.919510,10.704580,Private room,953.0,1,632,2025-09-25,4.28,2,341,63,NaN
54,1771222,Spacious room with privat bathroom in historic...,7121844,Line-Kirsti,NaN,Frogner,59.919180,10.702730,Private room,965.0,1,504,2025-09-24,3.48,2,313,94,NaN

On peut aussi utiliser des conjonctions logiques mais il faut se souvenir d'utiliser des parenthèses

**Remarque**: les expressions `and` et  `or` expressions ne fonctionnent pas dans ce cadre. On doit utiliser `&` et `|`.

In [32]:
df_listings.loc[(df_listings['number_of_reviews']>300) &
                (df_listings['reviews_per_month']>7), 
                :].head()

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365,number_of_reviews_ltm,license
19,761018,Lovely bedroom in beautiful area.,4011871,Mona Johanne,NaN,Frogner,59.91755,10.71428,Private room,443.0,1,1271,2025-09-24,8.16,1,0,86,NaN
405,12651632,central and nice room.Great location,68715154,Kumiko,NaN,Frogner,59.93111,10.71555,Private room,557.0,1,866,2025-09-14,7.82,1,169,127,NaN
774,20881638,Nordic room with easy access from/to the Airport!,149959085,Sarah & Alex,NaN,Grünerløkka,59.92558,10.77562,Private room,762.0,1,710,2025-09-23,7.25,2,205,54,NaN
1889,51244826,Room 1 - Cozy loft room in the heart of Oslo,24152273,John Dominick,NaN,Sentrum,59.91028,10.74246,Private room,802.0,2,380,2025-09-28,7.53,2,262,90,NaN
2146,573299694542694586,Room by Oslo Central Station & Bus Terminal,374009,Jan,NaN,Gamle Oslo,59.90946,10.76363,Private room,793.0,1,397,2025-09-19,9.25,13,235,42,NaN

Pour une seule colonne(i.e., un objet de type Series) on peut obtenir les valeurs prises on utilisant la fonction `unique()`.

In [33]:
df_listings['neighbourhood'].unique()

array(['Frogner', 'Gamle Oslo', 'St. Hanshaugen', 'Sagene', 'Nordstrand',
       'Grünerløkka', 'Nordre Aker', 'Sentrum', 'Bjerke', 'Vestre Aker',
       'Ullern', 'Søndre Nordstrand', 'Østensjø', 'Alna', 'Grorud',
       'Stovner', 'Marka'], dtype=object)

Pour plusieurs colonnes, on peut utiliser la fonction `drop_duplicates`.

In [34]:
df_listings[['neighbourhood', 'room_type']].drop_duplicates()

          neighbourhood        room_type
0               Frogner  Entire home/apt
1            Gamle Oslo     Private room
2            Gamle Oslo  Entire home/apt
3        St. Hanshaugen     Private room
4                Sagene     Private room
5                Sagene  Entire home/apt
6            Nordstrand  Entire home/apt
9           Grünerløkka     Private room
10          Grünerløkka  Entire home/apt
14          Nordre Aker  Entire home/apt
16       St. Hanshaugen  Entire home/apt
17              Sentrum     Private room
19              Frogner     Private room
29               Bjerke  Entire home/apt
34          Vestre Aker  Entire home/apt
45           Nordstrand     Private room
48               Ullern  Entire home/apt
74          Vestre Aker     Private room
79               Ullern     Private room
97    Søndre Nordstrand  Entire home/apt
142            Østensjø     Private room
159                Alna  Entire home/apt
188          Gamle Oslo      Shared room
216            Østensjø  Entire home/apt
221             Sentrum  Entire home/apt
236         Nordre Aker     Private room
239                Alna     Private room
277              Ullern      Shared room
314              Grorud     Private room
350             Stovner  Entire home/apt
504               Marka  Entire home/apt
671      St. Hanshaugen      Shared room
681              Bjerke     Private room
733              Grorud  Entire home/apt
793   Søndre Nordstrand     Private room
1905              Marka     Private room
2122         Nordstrand      Shared room
2858        Vestre Aker      Shared room
3593            Stovner     Private room
5914            Frogner      Shared room
6642        Grünerløkka      Shared room
8653  Søndre Nordstrand      Shared room
8971               Alna      Shared room
9577             Grorud      Shared room
9966            Sentrum      Shared room

### <center>5. AGGREGATION ET TABLEAUX CROISÉS </center>

Pour calculer des statistiques par groupe on peut utiliser la fonction `.groupby()`.

In [35]:
df_listings.groupby('neighbourhood')[['price', 'reviews_per_month']].mean()

                         price  reviews_per_month
neighbourhood
Alna               1017.024242           1.051256
Bjerke             1754.450644           1.128008
Frogner            2263.572860           1.332286
Gamle Oslo         1642.560026           1.452637
Grorud             2075.177778           0.925946
Grünerløkka        1436.536541           1.217847
Marka              1639.864865           1.240638
Nordre Aker        1517.772586           0.965673
Nordstrand         2244.875676           0.768109
Sagene             1307.576458           0.858546
Sentrum            1749.382857           2.947941
St. Hanshaugen     1609.990157           1.365392
Stovner            1048.810811           1.565152
Søndre Nordstrand  1328.448276           0.961589
Ullern             1599.196364           1.091767
Vestre Aker        2015.913669           0.751475
Østensjø           1537.570136           1.071224

Si l'on souhaite appliquer plus d'une fonction et notamment sur plusieurs colonnes, on peut utiliser `.aggregate()` qui est abrégée en  `.agg()`. Son argument est un dictionnaire où les variables sont les clés et les valeurs sont des listes de fonctions.

In [36]:
df_listings.groupby('neighbourhood').agg({"reviews_per_month": ["mean"],
                                          "price": ["min", np.max]}).reset_index()

        neighbourhood reviews_per_month  price
                                   mean    min      amax
0                Alna          1.051256  251.0   21750.0
1              Bjerke          1.128008  390.0   80000.0
2             Frogner          1.332286  312.0   93342.0
3          Gamle Oslo          1.452637  261.0   71500.0
4              Grorud          0.925946  319.0   52430.0
5         Grünerløkka          1.217847  375.0   20000.0
6               Marka          1.240638  324.0    5514.0
7         Nordre Aker          0.965673  200.0    9030.0
8          Nordstrand          0.768109  342.0   21750.0
9              Sagene          0.858546  400.0   18000.0
10            Sentrum          2.947941  367.0   10335.0
11     St. Hanshaugen          1.365392  277.0  116677.0
12            Stovner          1.565152  286.0    3600.0
13  Søndre Nordstrand          0.961589  297.0    8100.0
14             Ullern          1.091767  349.0   10040.0
15        Vestre Aker          0.751475  356.0   17600.0
16           Østensjø          1.071224  292.0   24000.0

Le problème avec cette syntaxe est qu'elle génère une structure hiérarchique pour les noms des variables, avec laquelle il peut être difficile de travailler. Dans l'exemple précédent pour accéder au prix moyen on doit utiliser `df.price["min"]`.

Pour faire simultanément l'agrégation et renommer les variables, on peut utiliser la syntaxe:  `agg(output_var = ("input_var", function))`.

In [37]:
df_listings.groupby('neighbourhood').agg(mean_reviews=("reviews_per_month", "mean"),
                                         min_price=("price", "min"),
                                         max_price=("price", np.max)).reset_index()

        neighbourhood  mean_reviews  min_price  max_price
0                Alna      1.051256      251.0    21750.0
1              Bjerke      1.128008      390.0    80000.0
2             Frogner      1.332286      312.0    93342.0
3          Gamle Oslo      1.452637      261.0    71500.0
4              Grorud      0.925946      319.0    52430.0
5         Grünerløkka      1.217847      375.0    20000.0
6               Marka      1.240638      324.0     5514.0
7         Nordre Aker      0.965673      200.0     9030.0
8          Nordstrand      0.768109      342.0    21750.0
9              Sagene      0.858546      400.0    18000.0
10            Sentrum      2.947941      367.0    10335.0
11     St. Hanshaugen      1.365392      277.0   116677.0
12            Stovner      1.565152      286.0     3600.0
13  Søndre Nordstrand      0.961589      297.0     8100.0
14             Ullern      1.091767      349.0    10040.0
15        Vestre Aker      0.751475      356.0    17600.0
16           Østensjø      1.071224      292.0    24000.0

Pour faire de tableaux croisés on utilise la fonction `.pivot_table()` dont les arguments sont:
- `index`: lignes,
- `columns`: colonnes,
- `values`: valeurs
- `aggfunc`: fonction d'agrégation.

In [38]:
df_listings.pivot_table(index='neighbourhood', columns='room_type', values='price', aggfunc='mean')

room_type          Entire home/apt  Private room  Shared room
neighbourhood
Alna                   1123.521277    861.971014  1361.000000
Bjerke                 1566.901554   2659.375000          NaN
Frogner                2406.944681    882.737705          NaN
Gamle Oslo             1757.990566    820.525714   472.769231
Grorud                 2869.551724    631.333333   696.000000
Grünerløkka            1509.339088    896.359375   584.500000
Marka                  1767.636364    585.750000          NaN
Nordre Aker            1577.306397    781.041667          NaN
Nordstrand             2401.429003    924.894737   585.000000
Sagene                 1335.654930    887.877193          NaN
Sentrum                1850.307692    983.058824   391.000000
St. Hanshaugen         1743.299320    759.333333   502.857143
Stovner                1393.181818    543.733333          NaN
Søndre Nordstrand      1542.735632    690.071429   560.000000
Ullern                 1715.529915    938.625000   800.000000
Vestre Aker            2133.924686   1312.736842   532.000000
Østensjø               1808.425287    534.829787          NaN